feat: added connect util fn
nartc/ngxtension-platform pull request #23
Opened 2023-09-11 15:42 UTC by eneajaho

closes #7

2023-09-11 17:00 UTC, nartc requested changes

2023-09-11 17:05 UTC, eneajaho commented on libs/ngxtension/connect/src/connect.ts
> +		destroyRef = injector?.get(DestroyRef, null) || inject(DestroyRef);
What if we don't pass an injector at all? 😅

2023-09-11 17:05 UTC, eneajaho commented on libs/ngxtension/connect/src/connect.spec.ts
> +			}).compileComponents();
Using default tests for components. 😅

2023-09-11 17:06 UTC, nartc commented on libs/ngxtension/connect/src/connect.ts
> +		destroyRef = injector?.get(DestroyRef, null) || inject(DestroyRef);
`assertInjector` gives you the default `Injector` if you're in an `InjectionContext` with `inject(Injector)`

2023-09-12 20:56 UTC, nartc approved these changes

2023-09-12 21:33 UTC, merged